import type { ScrimListing } from "./types";

/**
 * Seed scrim listings for milestone 1. ~14 rows spread across the four games,
 * real PH universities, per-game ranks, ratings 1400–2100, reliability 70–99,
 * mixed verification, varied availability windows. Replaced by Supabase data
 * in a later milestone.
 */
export const SCRIM_LISTINGS: ScrimListing[] = [
  // ── Mobile Legends: Bang Bang ─────────────────────────────────────────────
  {
    id: "mlbb-up",
    game: "mlbb",
    teamName: "UP Fighting Maroons Esports",
    school: "University of the Philippines",
    verified: true,
    rating: 1988,
    reliability: 96,
    availability: "Tonight 8:00–11:00 PM",
    timeWindow: "Tonight",
    format: "BO3",
    rankBand: "Mythical Glory–Mythical Honor",
    rankTiers: ["Mythical Glory", "Mythical Honor"],
  },
  {
    id: "mlbb-dlsu",
    game: "mlbb",
    teamName: "DLSU Green Gaming",
    school: "De La Salle University",
    verified: true,
    rating: 1902,
    reliability: 91,
    availability: "Tonight 9:00 PM–12:00 AM",
    timeWindow: "Tonight",
    format: "BO5",
    rankBand: "Mythical Honor",
    rankTiers: ["Mythical Honor"],
  },
  {
    id: "mlbb-admu",
    game: "mlbb",
    teamName: "Ateneo Blue Spark",
    school: "Ateneo de Manila University",
    verified: false,
    rating: 1740,
    reliability: 84,
    availability: "This week · Wed–Fri evenings",
    timeWindow: "This Week",
    format: "Scrim Block",
    rankBand: "Mythic–Mythical Glory",
    rankTiers: ["Mythic", "Mythical Glory"],
  },
  {
    id: "mlbb-ust",
    game: "mlbb",
    teamName: "UST Growling Tigers Esports",
    school: "University of Santo Tomas",
    verified: true,
    rating: 1663,
    reliability: 78,
    availability: "Weekend · Sat 2:00–6:00 PM",
    timeWindow: "Weekend",
    format: "BO2",
    rankBand: "Mythic",
    rankTiers: ["Mythic"],
  },

  // ── Valorant ─────────────────────────────────────────────────────────────
  {
    id: "val-mapua",
    game: "valorant",
    teamName: "Mapúa Cardinals VCT",
    school: "Mapúa University",
    verified: true,
    rating: 2044,
    reliability: 97,
    availability: "Tonight 7:30–10:30 PM",
    timeWindow: "Tonight",
    format: "BO3",
    rankBand: "Immortal–Radiant",
    rankTiers: ["Immortal", "Radiant"],
  },
  {
    id: "val-feu",
    game: "valorant",
    teamName: "FEU Tamaraws Tactical",
    school: "Far Eastern University",
    verified: false,
    rating: 1815,
    reliability: 88,
    availability: "This week · Tue/Thu 8:00 PM",
    timeWindow: "This Week",
    format: "BO1",
    rankBand: "Ascendant–Immortal",
    rankTiers: ["Ascendant", "Immortal"],
  },
  {
    id: "val-nu",
    game: "valorant",
    teamName: "NU Bulldogs Valorant",
    school: "National University",
    verified: true,
    rating: 1590,
    reliability: 73,
    availability: "Weekend · Sun 1:00–5:00 PM",
    timeWindow: "Weekend",
    format: "Scrim Block",
    rankBand: "Ascendant",
    rankTiers: ["Ascendant"],
  },
  {
    id: "val-adamson",
    game: "valorant",
    teamName: "Adamson Soaring Falcons",
    school: "Adamson University",
    verified: false,
    rating: 1452,
    reliability: 81,
    availability: "Tonight 10:00 PM–1:00 AM",
    timeWindow: "Tonight",
    format: "BO2",
    rankBand: "Diamond–Ascendant",
    rankTiers: ["Diamond", "Ascendant"],
  },

  // ── Dota 2 ───────────────────────────────────────────────────────────────
  {
    id: "dota-upcebu",
    game: "dota",
    teamName: "UP Cebu Warriors Dota",
    school: "UP Cebu",
    verified: false,
    rating: 1930,
    reliability: 90,
    availability: "This week · Mon–Thu 9:00 PM",
    timeWindow: "This Week",
    format: "BO3",
    rankBand: "5k–6k+ MMR",
    rankTiers: ["5k MMR", "6k+ MMR"],
  },
  {
    id: "dota-ustp",
    game: "dota",
    teamName: "USTP Cyclones",
    school: "University of Science and Technology of Southern Philippines",
    verified: true,
    rating: 1706,
    reliability: 85,
    availability: "Weekend · Sat 7:00–11:00 PM",
    timeWindow: "Weekend",
    format: "BO5",
    rankBand: "4k–5k MMR",
    rankTiers: ["4k MMR", "5k MMR"],
  },
  {
    id: "dota-silliman",
    game: "dota",
    teamName: "Silliman Stallions Esports",
    school: "Silliman University",
    verified: false,
    rating: 1497,
    reliability: 76,
    availability: "Tonight 8:30–11:30 PM",
    timeWindow: "Tonight",
    format: "BO1",
    rankBand: "4k MMR",
    rankTiers: ["4k MMR"],
  },

  // ── Call of Duty: Mobile ─────────────────────────────────────────────────
  {
    id: "codm-batstate",
    game: "codm",
    teamName: "Batangas State Red Spartans",
    school: "Batangas State University",
    verified: true,
    rating: 2071,
    reliability: 99,
    availability: "Tonight 9:00 PM–12:00 AM",
    timeWindow: "Tonight",
    format: "BO5",
    rankBand: "Grand Master–Legendary",
    rankTiers: ["Grand Master", "Legendary"],
  },
  {
    id: "codm-feu",
    game: "codm",
    teamName: "FEU Tamaraws Mobile",
    school: "Far Eastern University",
    verified: false,
    rating: 1638,
    reliability: 79,
    availability: "This week · Wed/Fri 8:30 PM",
    timeWindow: "This Week",
    format: "BO3",
    rankBand: "Master–Grand Master",
    rankTiers: ["Master", "Grand Master"],
  },
  {
    id: "codm-nu",
    game: "codm",
    teamName: "NU Bulldogs CoDM",
    school: "National University",
    verified: true,
    rating: 1571,
    reliability: 70,
    availability: "Weekend · Sun 3:00–7:00 PM",
    timeWindow: "Weekend",
    format: "Scrim Block",
    rankBand: "Master",
    rankTiers: ["Master"],
  },
];
